const APP = Object.freeze({
  NAME: 'Fedes Landing CMS',
  VERSION: '4.4.0',
  SCHEMA_VERSION: 4,
  LOCALE: 'es-AR',
  TIMEZONE: 'America/Argentina/Buenos_Aires',
  CURRENCY: 'ARS',
  CACHE_TTL_SECONDS: 300,
  ADMIN_SESSION_TTL_SECONDS: 21600,
  MAX_MEDIA_BYTES: 8 * 1024 * 1024,
  PUBLIC_STATUSES: ['published'],
  STATUS: Object.freeze({
    DRAFT: 'draft',
    PUBLISHED: 'published',
    HIDDEN: 'hidden',
    ARCHIVED: 'archived',
  }),
  SHEETS: Object.freeze({
    SYSTEM: '_System',
    AUDIT: '_AuditLog',
    SETTINGS: 'CMS_Settings',
    CONTENT: 'CMS_Content',
    MODULES: 'CMS_OnboardingModules',
    CASES: 'CMS_CaseStudies',
    TESTIMONIALS: 'CMS_Testimonials',
    TEAM: 'CMS_Team',
    BLOG: 'CMS_BlogPosts',
    GALLERY: 'CMS_Gallery',
    MEDIA: 'CMS_Media',
    CONTACTS: 'CRM_Contacts',
    CAMPAIGNS: 'CRM_Campaigns',
    CAMPAIGN_LANDINGS: 'CRM_CampaignLandings',
    LEADS: 'CRM_Leads',
    LEAD_ANSWERS: 'CRM_LeadAnswers',
    LEAD_EVENTS: 'CRM_LeadEvents',
    LEAD_MAILINGS: 'CRM_LeadMailings',
    ONBOARDING: 'ONB_Records',
    ANALYTICS: 'AN_Events',
  }),
  PROPS: Object.freeze({
    SPREADSHEET_ID: 'FEDES_CMS_SPREADSHEET_ID',
    MEDIA_FOLDER_ID: 'FEDES_CMS_MEDIA_FOLDER_ID',
    ADMIN_PASSWORD_HASH: 'FEDES_CMS_ADMIN_PASSWORD_HASH',
    ADMIN_PASSWORD_SALT: 'FEDES_CMS_ADMIN_PASSWORD_SALT',
    VADDAR_API_KEY_HASH: 'FEDES_CMS_VADDAR_API_KEY_HASH',
    VADDAR_API_KEY_SALT: 'FEDES_CMS_VADDAR_API_KEY_SALT',
    SETUP_COMPLETE: 'FEDES_CMS_SETUP_COMPLETE',
    LEGACY_MIGRATION_DONE: 'FEDES_CMS_LEGACY_MIGRATION_V1_DONE',
    CAMPAIGN_LANDINGS_MIGRATION_DONE: 'FEDES_CMS_CAMPAIGN_LANDINGS_V1_DONE',
  }),
  LEGACY_SHEETS: Object.freeze({
    CONTACTS: 'Respuestas_Contacto',
    TRACKING: 'Tracking_Clicks',
    BLOG: 'Publicaciones_Blog',
    GALLERY: 'Galeria_Fotos',
    ONBOARDING_PROGRESS: 'OnboardingProgress',
    ONBOARDING_STEP0: 'OnboardingEmpresas_Step0',
    ONBOARDING_STEP1: 'OnboardingEmpresas_Step1',
  }),
});

const ENTITY_DEFS = Object.freeze({
  content: {
    sheet: APP.SHEETS.CONTENT,
    pk: 'content_id',
    label: 'Contenido',
    fields: ['content_key','section','title','subtitle','body','cta_label','cta_url','media_id','sort_order','featured','status','metadata_json'],
  },
  onboardingModules: {
    sheet: APP.SHEETS.MODULES,
    pk: 'module_id',
    label: 'Módulos de onboarding',
    fields: ['module_key','title','description','deliverable','value_text','media_id','accent_color','sort_order','featured','status','metadata_json'],
  },
  caseStudies: {
    sheet: APP.SHEETS.CASES,
    pk: 'case_id',
    label: 'Casos de éxito',
    fields: ['case_key','tag','stat','result_text','media_id','poster_url','video_mp4_url','video_webm_url','sort_order','featured','status','metadata_json'],
  },
  testimonials: {
    sheet: APP.SHEETS.TESTIMONIALS,
    pk: 'testimonial_id',
    label: 'Testimonios',
    fields: ['testimonial_key','company','person_name','person_role','quote','logo_media_id','sort_order','featured','status','metadata_json'],
  },
  team: {
    sheet: APP.SHEETS.TEAM,
    pk: 'team_id',
    label: 'Equipo',
    fields: ['team_key','name','role','bio','linkedin_url','media_id','sort_order','featured','status','metadata_json'],
  },
  blogPosts: {
    sheet: APP.SHEETS.BLOG,
    pk: 'post_id',
    label: 'Blog',
    fields: ['slug','title','description','content','author','published_at','media_id','image_url','external_url','sort_order','featured','status','metadata_json'],
  },
  gallery: {
    sheet: APP.SHEETS.GALLERY,
    pk: 'gallery_id',
    label: 'Galería',
    fields: ['title','caption','media_id','external_url','alt_text','sort_order','featured','status','metadata_json'],
  },
  campaigns: {
    sheet: APP.SHEETS.CAMPAIGNS,
    pk: 'campaign_id',
    label: 'Campañas',
    fields: ['campaign_key','name','landing_path','benefit_label','meeting_url','starts_at','ends_at','sort_order','featured','status','metadata_json'],
  },
  campaignLandings: {
    sheet: APP.SHEETS.CAMPAIGN_LANDINGS,
    pk: 'landing_id',
    label: 'Landings de campaña',
    fields: ['campaign_key','landing_key','name','path','benefit_label','benefit_percent','badge','kicker','headline','headline_accent','description','seo_title','seo_description','source_default','utm_source_default','utm_medium_default','utm_campaign_default','sort_order','featured','status','metadata_json'],
  },
  settings: {
    sheet: APP.SHEETS.SETTINGS,
    pk: 'setting_id',
    label: 'Ajustes',
    fields: ['setting_key','setting_value','value_type','group_name','description','status'],
  },
});