const SCHEMA = Object.freeze({
  '_System': ['key','value','updated_at'],
  '_AuditLog': ['audit_id','actor','actor_type','entity','entity_id','action','before_json','after_json','source','created_at'],
  'CMS_Settings': ['setting_id','setting_key','setting_value','value_type','group_name','description','status','created_at','updated_at','archived_at'],
  'CMS_Content': ['content_id','content_key','section','title','subtitle','body','cta_label','cta_url','media_id','sort_order','featured','status','metadata_json','created_at','updated_at','archived_at'],
  'CMS_OnboardingModules': ['module_id','module_key','title','description','deliverable','value_text','media_id','accent_color','sort_order','featured','status','metadata_json','created_at','updated_at','archived_at'],
  'CMS_CaseStudies': ['case_id','case_key','tag','stat','result_text','media_id','poster_url','video_mp4_url','video_webm_url','sort_order','featured','status','metadata_json','created_at','updated_at','archived_at'],
  'CMS_Testimonials': ['testimonial_id','testimonial_key','company','person_name','person_role','quote','logo_media_id','sort_order','featured','status','metadata_json','created_at','updated_at','archived_at'],
  'CMS_Team': ['team_id','team_key','name','role','bio','linkedin_url','media_id','sort_order','featured','status','metadata_json','created_at','updated_at','archived_at'],
  'CMS_BlogPosts': ['post_id','slug','title','description','content','author','published_at','media_id','image_url','external_url','sort_order','featured','status','metadata_json','created_at','updated_at','archived_at'],
  'CMS_Gallery': ['gallery_id','title','caption','media_id','external_url','alt_text','sort_order','featured','status','metadata_json','created_at','updated_at','archived_at'],
  'CMS_Media': ['media_id','file_id','file_name','mime_type','file_size','drive_url','public_url','alt_text','entity_type','entity_id','sort_order','status','metadata_json','created_at','updated_at','archived_at'],
  'CRM_Contacts': ['contact_id','created_at','updated_at','full_name','email','phone','company','message','source','page_path','status','metadata_json','archived_at'],
  'CRM_Campaigns': ['campaign_id','campaign_key','name','landing_path','benefit_label','meeting_url','starts_at','ends_at','sort_order','featured','status','metadata_json','created_at','updated_at','archived_at'],
  'CRM_CampaignLandings': ['landing_id','campaign_key','landing_key','name','path','benefit_label','benefit_percent','badge','kicker','headline','headline_accent','description','seo_title','seo_description','source_default','utm_source_default','utm_medium_default','utm_campaign_default','sort_order','featured','status','metadata_json','created_at','updated_at','archived_at'],
  'CRM_Leads': ['lead_id','campaign_key','landing_key','source','status','stage','full_name','email','company','website','phone','score_total','knockout','classification','benefit','mailing_segment','utm_source','utm_medium','utm_campaign','utm_content','referrer','consent_marketing','current_step','last_question_key','last_activity_at','manual_review_status','owner','next_action_at','resume_token_hash','resume_expires_at','meeting_status','meeting_clicked_at','created_at','updated_at','completed_at','archived_at','metadata_json'],
  'CRM_LeadAnswers': ['answer_id','lead_id','campaign_key','question_key','answer_key','answer_text','score','knockout','created_at','updated_at','archived_at'],
  'CRM_LeadEvents': ['event_id','lead_id','campaign_key','landing_key','event_type','page_path','source','metadata_json','created_at'],
  'CRM_LeadMailings': ['mailing_id','lead_id','campaign_key','segment','template_key','sequence_no','status','scheduled_at','sent_at','opened_at','clicked_at','provider','provider_message_id','attempt_count','error_message','metadata_json','created_at','updated_at','archived_at'],
  'ONB_Records': ['onboarding_id','cuit','company_name','contact_name','email','taxpayer_type','current_step','status','is_completed','data_json','created_at','updated_at','completed_at','archived_at'],
  'AN_Events': ['event_id','category','label','value','page_path','session_id','source','metadata_json','created_at'],
});

const PRIMARY_KEYS = Object.freeze({
  '_AuditLog': 'audit_id',
  'CMS_Settings': 'setting_id',
  'CMS_Content': 'content_id',
  'CMS_OnboardingModules': 'module_id',
  'CMS_CaseStudies': 'case_id',
  'CMS_Testimonials': 'testimonial_id',
  'CMS_Team': 'team_id',
  'CMS_BlogPosts': 'post_id',
  'CMS_Gallery': 'gallery_id',
  'CMS_Media': 'media_id',
  'CRM_Contacts': 'contact_id',
  'CRM_Campaigns': 'campaign_id',
  'CRM_CampaignLandings': 'landing_id',
  'CRM_Leads': 'lead_id',
  'CRM_LeadAnswers': 'answer_id',
  'CRM_LeadEvents': 'event_id',
  'CRM_LeadMailings': 'mailing_id',
  'ONB_Records': 'onboarding_id',
  'AN_Events': 'event_id',
});
